### ISSUE TITLE
Merge this fork back into the main repo

### ISSUE THREAD

**Issue by AnotherFoxGuy** [AnotherFoxGuy/pmm#42]
Since the main repo is active again I think it would be a good time to merge all the changes back into te main repo

## TODO

- [x] #5 
- [x] #8 
- [x] #12 
- [ ] #15 <-- maybe?
- [ ] #19 
- [x] #22 
- [ ] #25
- [ ] #26
- [x] #38
- [ ] #41
- [x] Added VCPKG PORTS for copying custom ports
- [ ] Fixed finding python on AppVeyor
- [x] Added Clean helper command
